### ISSUE TITLE
`Unable to apply patch 'footnote'` warning and footnote hyperlink failures due to `setspace` being loaded after `hyperref`

### ISSUE THREAD

**Issue by zixingjiang** [gboeing/cv#6]
Hi Prof. Boeing, thanks for sharing your wonderful template. I noticed a small problem with the .tex file that I would like to point out and offer a solution.

## Description

When the `setspace` package is loaded after the `hyperref` package, it leads to the warning `Unable to apply patch 'footnote'` and breaks footnote hyperlinks because `setspace` overwrites `hyperref`'s definition of `\@footnotetext`, as explained [here](https://github.com/schlcht/microtype/issues/11). This issue can be resolved by loading `setspace` package before the `hyperref` package.

## Steps to Preproduce

1. Load the `setspace` package after the `hyperref` package in the LaTeX document preamble.
2. Compile the document.
3. Observe warnings in the log and check footnote hyperlinks in the compiled PDF. 

## Excepted Behavior

The document should compile without warnings, and all footnote hyperlinks should work correctly.

## Actual Behavior

The document compilation produces the warning `Unable to apply patch 'footnote'`, and footnote hyperlinks always point to the beginning of the document.

![warnings](https://github.com/user-attachments/assets/89ef53d8-fc32-4ddf-bd4f-0bd46a3effd3)

## Solution 

Load the `setspace` package before the `hyperref` package in the LaTeX document preamble.

**Comment by gboeing** [comment]
Thanks. Resolved by 677f371.
